### ISSUE TITLE
Update Sub Timer for Spongeathon 2023

### ISSUE THREAD

**Issue by the-ivo-robotnic** [shift-devs/donation-timer#1]
A list of ToDo Itemsto prepare the sub-timer for Spongeathon 2023.

This may be broken up into dedicated issues later.

Critical:
* Allow for end-user configuration of time-values per each donation/subscription type
* Remove or disable "Donation Combo Mode"

Nice to Have:
* Allow for end-user to toggle between "Donation Combo Mode" and flat-rates for time-values

**Comment by AaronRules5** [comment]
Old issue; I believe these are implemented by now? (Except for the Nice to Have one)
Feel free to create a new issue if I made a mistake.
